# Generated by Django 4.1.5 on 2023-02-01 11:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_jobapplies_payslip'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_names', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('position', models.CharField(max_length=50)),
                ('cover_letter', models.TextField()),
                ('cv', models.FileField(null=True, upload_to='candidates/cv/')),
            ],
            options={
                'verbose_name': 'Job Applies',
                'verbose_name_plural': 'Job Appliess',
            },
        ),
        migrations.CreateModel(
            name='Vacancie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Vacancie',
                'verbose_name_plural': 'Vacancies',
            },
        ),
        migrations.CreateModel(
            name='ViewedVacancie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacancie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.vacancie')),
            ],
            options={
                'verbose_name': 'ViewedVacancie',
                'verbose_name_plural': 'ViewedVacancies',
            },
        ),
        migrations.DeleteModel(
            name='JobApplies',
        ),
        migrations.AddField(
            model_name='employee',
            name='dob',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='vacancie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.vacancie'),
        ),
    ]
